# Generated by Django 5.2.9 on 2025-12-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingreso_descripcion_alter_gasto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
